/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobasecaliza;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge García
 */
public class VCrearRetencion extends javax.swing.JFrame {

    /**
     * Creates new form VCrearRetencion
     */
    public VCrearRetencion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloCrear = new javax.swing.JLabel();
        lbIdRetencion = new javax.swing.JLabel();
        Porcentaje = new javax.swing.JLabel();
        tfIdRetencion = new javax.swing.JTextField();
        tfPorcentaje = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfValorRetenido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfIdFactura = new javax.swing.JTextField();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Retención");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloCrear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTituloCrear.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloCrear.setText("Crear Retención");
        getContentPane().add(lbTituloCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 220, 50));

        lbIdRetencion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbIdRetencion.setForeground(new java.awt.Color(255, 255, 255));
        lbIdRetencion.setText("Id Retención");
        getContentPane().add(lbIdRetencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        Porcentaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Porcentaje.setForeground(new java.awt.Color(255, 255, 255));
        Porcentaje.setText("Porcentaje");
        getContentPane().add(Porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        tfIdRetencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdRetencionActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdRetencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 190, -1));

        tfPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPorcentajeActionPerformed(evt);
            }
        });
        getContentPane().add(tfPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valor Retenido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(tfValorRetenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id Factura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        getContentPane().add(tfIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, -1));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobasecaliza/Fondo 1.jpg"))); // NOI18N
        lbFondo.setText("jLabel1");
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdRetencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdRetencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdRetencionActionPerformed

    private void tfPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPorcentajeActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Connection cn = Sistema.getNewAccess().getConn();
        CallableStatement mycall;
        try {
            mycall =cn.prepareCall("{call insertReten('"+tfIdRetencion.getText()+"', "+tfPorcentaje.getText()+", "+tfValorRetenido.getText()+", '"+tfIdFactura.getText()+"')}");
            mycall.execute();
            JOptionPane notificacion = new JOptionPane();
            this.tfIdRetencion.setText("");
            this.tfPorcentaje.setText("");
            this.tfValorRetenido.setText("");
            this.tfIdFactura.setText("");
            notificacion.showMessageDialog(rootPane, "Retencion ingresada exitosamente", "Crear Retencion", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException se) {
            se.printStackTrace();
        }
        
        

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VPrincipal ventana= new VPrincipal();
        ventana.setLocation(this.getLocation());
        this.dispose();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCrearRetencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCrearRetencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCrearRetencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCrearRetencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCrearRetencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Porcentaje;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbIdRetencion;
    private javax.swing.JLabel lbTituloCrear;
    private javax.swing.JTextField tfIdFactura;
    private javax.swing.JTextField tfIdRetencion;
    private javax.swing.JTextField tfPorcentaje;
    private javax.swing.JTextField tfValorRetenido;
    // End of variables declaration//GEN-END:variables
}
