/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobasecaliza;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyectobasecaliza.sistema.FormaPago;

/**
 *
 * @author Jorge García
 */
public class VCrearPagoDeposito extends javax.swing.JFrame {

    /**
     * Creates new form VCrearPago
     */
    public VCrearPagoDeposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNumComprobante = new javax.swing.JTextField();
        tfFechaEmi = new javax.swing.JTextField();
        tfbcoDeposito = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCtaDeposito = new javax.swing.JTextField();
        tfValorCancelado = new javax.swing.JTextField();
        tfNumFactura = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jcFormasPago = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(370, 330));
        setPreferredSize(new java.awt.Dimension(370, 330));
        setResizable(false);

        jpContent.setBackground(new java.awt.Color(102, 153, 255));
        jpContent.setMinimumSize(new java.awt.Dimension(370, 525));
        jpContent.setPreferredSize(new java.awt.Dimension(370, 525));
        jpContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Pago");
        jpContent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero Comprobante:");
        jpContent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de pago:");
        jpContent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Banco Deposito");
        jpContent.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jpContent.add(tfNumComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 120, -1));
        jpContent.add(tfFechaEmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        tfbcoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbcoDepositoActionPerformed(evt);
            }
        });
        jpContent.add(tfbcoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 120, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jpContent.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta Deposito");
        jpContent.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor cancelado");
        jpContent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Num Factura");
        jpContent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Id forma de pago");
        jpContent.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        jpContent.add(tfCtaDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, -1));
        jpContent.add(tfValorCancelado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 120, -1));
        jpContent.add(tfNumFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jpContent.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jcFormasPago.setModel(new DefaultComboBoxModel(Sistema.getFormasPago().toArray()));
        jcFormasPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcFormasPagoActionPerformed(evt);
            }
        });
        jpContent.add(jcFormasPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 120, -1));

        getContentPane().add(jpContent, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 386, 369);
    }// </editor-fold>//GEN-END:initComponents

    private void tfbcoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfbcoDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfbcoDepositoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VPrincipal ventana= new VPrincipal();
        ventana.setLocation(this.getLocation());
        this.dispose();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        FormaPago fp = null;
        try {
            for(FormaPago f : Sistema.getFormasPago()){
                if(f.toString().equals(jcFormasPago.getSelectedItem().toString())) fp=f;
            }
            Sistema.getNewAccess().write2("{call insertPaymeDeposito('"+tfNumComprobante.getText()+"', '"+tfFechaEmi.getText()+"', '"+tfbcoDeposito.getText()+"', '"+tfCtaDeposito.getText()+"', "+tfValorCancelado.getText()+", '"+tfNumFactura.getText()+"','"+fp.getId()+"')}");
            JOptionPane notificacion = new JOptionPane();
            this.tfNumComprobante.setText("");
            this.tfFechaEmi.setText("");
            this.tfbcoDeposito.setText("");
            this.tfCtaDeposito.setText("");
            this.tfValorCancelado.setText("");
            this.tfNumFactura.setText("");
            this.jcFormasPago.setSelectedIndex(-1);
            notificacion.showMessageDialog(rootPane, "Pago ingresado exitosamente", "Pago con deposito", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void jcFormasPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcFormasPagoActionPerformed
        
    }//GEN-LAST:event_jcFormasPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCrearPagoDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCrearPagoDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCrearPagoDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCrearPagoDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCrearPagoDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcFormasPago;
    private javax.swing.JPanel jpContent;
    private javax.swing.JTextField tfCtaDeposito;
    private javax.swing.JTextField tfFechaEmi;
    private javax.swing.JTextField tfNumComprobante;
    private javax.swing.JTextField tfNumFactura;
    private javax.swing.JTextField tfValorCancelado;
    private javax.swing.JTextField tfbcoDeposito;
    // End of variables declaration//GEN-END:variables
}
