/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobasecaliza;

/**
 *
 * @author Jorge García
 */
public class VLogin extends javax.swing.JFrame {

    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PInicio = new javax.swing.JPanel();
        lbIniciarSesion = new javax.swing.JLabel();
        lbNombreUsuario = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        FondoPanel = new javax.swing.JLabel();
        lbNombreEmpresa = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbIniciarSesion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbIniciarSesion.setText("Iniciar Sesion:");
        PInicio.add(lbIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lbNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreUsuario.setText("Nombre de Usuario:");
        PInicio.add(lbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        lbContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbContraseña.setText("Contraseña:");
        PInicio.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        PInicio.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        PInicio.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, -1));

        btnLogin.setText("Iniciar Sesion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        PInicio.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        FondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobasecaliza/fondos-de-pantalla-papers.co_.jpg"))); // NOI18N
        FondoPanel.setText("jLabel2");
        PInicio.add(FondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        getContentPane().add(PInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 410, 310));

        lbNombreEmpresa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreEmpresa.setText("Calizas S.A.");
        getContentPane().add(lbNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 190, 40));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 460, 70, -1));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobasecaliza/LoginCompositeBackground.png"))); // NOI18N
        lbFondo.setText("jLabel1");
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        VPrincipal ventana= new VPrincipal();
        ventana.setLocation(this.getLocation());
        this.dispose();
        ventana.setVisible(true);
        
        // String usuario=txtNombreUsuario.getText();
        // String contrasena=txtContraseña.getText();
         
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoPanel;
    private javax.swing.JPanel PInicio;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbIniciarSesion;
    private javax.swing.JLabel lbNombreEmpresa;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
