/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 14-jun-2012, 22:47:06
 */
package Interfacez;

import Clases.Dibuja;
import Clases.Algoritmo;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Tottus
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    private ArrayList<Integer> asient=new ArrayList<Integer>();
    private long x=0,y=0;
    private int Elem=0; 
    double quick=0,merg=0,shell=0;
    private Algoritmo c;
    private Object Quick[];
    private Object fusion[];
    private Object shellsort[];
    private Dibuja dibuj=new Dibuja();
     final XYSeries serie1 = new XYSeries("QuickSort");
     final XYSeries serie2 = new XYSeries("MergeSort");
     final XYSeries serie3 = new XYSeries("ShellSort");
     private XYSeriesCollection collection = new XYSeriesCollection();
     
    public Principal() {
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/titulo.png")).getImage());
        initComponents();
        this.setLocationRelativeTo(null);
        asient.clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspElems = new javax.swing.JScrollPane();
        listlemen = new javax.swing.JList();
        btnadd = new javax.swing.JButton();
        txtcantidad = new javax.swing.JTextField();
        jlbElems1 = new javax.swing.JLabel();
        btnsort = new javax.swing.JButton();
        jspElemsOrd = new javax.swing.JScrollPane();
        listsort = new javax.swing.JList();
        btnmerge = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listmerge = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listinser = new javax.swing.JList();
        btninser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblcant = new javax.swing.JLabel();
        savetime = new javax.swing.JButton();
        graficar = new javax.swing.JButton();
        memoria = new javax.swing.JLabel();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".:Analisis, Algoritmos de Ordenacion :. By Luis Paz Rumiche");
        setResizable(false);

        listlemen.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jspElems.setViewportView(listlemen);

        btnadd.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        txtcantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jlbElems1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jlbElems1.setText("Elementos:");

        btnsort.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnsort.setText("QuickSort");
        btnsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsortActionPerformed(evt);
            }
        });

        listsort.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jspElemsOrd.setViewportView(listsort);

        btnmerge.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnmerge.setText("MergeSort");
        btnmerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmergeActionPerformed(evt);
            }
        });

        listmerge.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(listmerge);

        listinser.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(listinser);

        btninser.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btninser.setText("ShellSort");
        btninser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Algoritmos de Ordenacion");

        lblcant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0), 2));

        savetime.setText("Guardar Tiempos");
        savetime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savetimeActionPerformed(evt);
            }
        });

        graficar.setText("Graficar");
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        memoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        memoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2));

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help_contents.gif"))); // NOI18N
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspElems, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbElems1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnsort, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jspElemsOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblcant, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(memoria, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnmerge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btninser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(savetime, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(help))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbElems1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsort)
                        .addComponent(btnmerge)
                        .addComponent(btninser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jspElemsOrd)
                    .addComponent(jspElems, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savetime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       try{
           Elem=Integer.parseInt(txtcantidad.getText());
           listlemen.setListData(Llenar(Elem).toArray());
           lblcant.setText(""+asient.size());
           c=new Algoritmo();//asient.toArray()
       }catch(NullPointerException e){
           JOptionPane.showMessageDialog(this, "Ingrese Una Cantidad de Elementos Valida");
       }
}//GEN-LAST:event_btnaddActionPerformed

    
    private void btnsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsortActionPerformed
        if(asient.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El Arreglo de Elementos Está Vacío !!!","Mensaje",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Algoritmo Quick=new Algoritmo(asient.toArray(), asient.size());
//        c=new Algoritmo(asient.toArray(), asient.size());
        Quick=null;
        Quick=asient.toArray();
        x=System.currentTimeMillis();
        c.quickSort(Quick, 0, Quick.length-1);
        y=System.currentTimeMillis();
        quick= ImprimeTiempos((y-x),"Elementos Ordenados Por QuickSort");
        listsort.setListData(Quick);
        
}//GEN-LAST:event_btnsortActionPerformed

    
    private void btnmergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmergeActionPerformed

        if(asient.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El Arreglo de Elementos Está Vacío !!!","Mensaje",JOptionPane.WARNING_MESSAGE);
            return;
        }
        fusion=null;
        fusion=asient.toArray();
        x=System.currentTimeMillis();
        c.mergesort(fusion, 0, asient.size());
        y=System.currentTimeMillis();
        merg=ImprimeTiempos((y-x),"Elementos Ordenados Por MergeSort");
        listmerge.setListData(fusion);
    }//GEN-LAST:event_btnmergeActionPerformed

    private void btninserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninserActionPerformed
        
        if(asient.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El Arreglo de Elementos Está Vacío !!!","Mensaje",JOptionPane.WARNING_MESSAGE);
            return;
        }
        shellsort=null;
        shellsort=asient.toArray();
        Algoritmo a=new Algoritmo();
        x=System.currentTimeMillis();
        a.shellSort(shellsort);
        y=System.currentTimeMillis();
        shell=ImprimeTiempos((y-x),"Elementos Ordenados Por Insercion");
        listinser.setListData(shellsort);

    }//GEN-LAST:event_btninserActionPerformed

    private void savetimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savetimeActionPerformed
            
            serie1.add(Elem,quick);
//            System.out.println(Elem+" , "+quick );
            serie2.add(Elem,merg);
//            System.out.println(Elem+" , "+merg );
            serie3.add(Elem,shell);
//            System.out.println(Elem+" , "+shell );
            memoria.setText("Quick: "+serie1.getItemCount()+"  Merg: "+serie2.getItemCount()+" Shell: "+serie3.getItemCount());
            JOptionPane.showMessageDialog(this, "Datos Agregados "+serie1.getItemCount());
    }//GEN-LAST:event_savetimeActionPerformed

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
        collection.removeAllSeries();
        collection.addSeries(serie1);
        collection.addSeries(serie2);
        collection.addSeries(serie3);
        Grafica grafic =new Grafica(this, true);
        JFreeChart chart=dibuj.CreaGrafica(collection);
//        chart.setTitle(".: Analisis de Algoritmos :.  By Luis Paz Rumiche");
        ChartPanel panel=new ChartPanel(chart);
        grafic.setContentPane(panel);
        grafic.setVisible(true);
     
    }//GEN-LAST:event_graficarActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        Ayuda ayuda=new Ayuda(this, true);
        ayuda.setVisible(true);
    }//GEN-LAST:event_helpActionPerformed
    public ArrayList<Integer> Llenar(int cantidad){
            asient.clear();
            x=0;y=0;
            x=System.currentTimeMillis();
            for(int i=0;i<cantidad;i++){
                asient.add(generanum(cantidad));
             }  
             y=System.currentTimeMillis();
             long seg=y-x;  
             BigDecimal bd=new BigDecimal(seg);
             bd.setScale(10);
             String c="Elementos Generados "+cantidad +"\n";
             ImprimeTiempos(seg, c);
        return asient;
      }

    public int generanum(int cantidad){
        return (int)(Math.random()*cantidad);
    }
    
    
    public double ImprimeTiempos(long seg,String c){
        BigDecimal bd=new BigDecimal(seg);
        bd.setScale(13);
        BigDecimal z=bd.divide(new BigDecimal(1000));
        double m=z.doubleValue();
        JOptionPane.showMessageDialog(null, "Tiempo : "+m+" seg.");
        return m;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btninser;
    private javax.swing.JButton btnmerge;
    private javax.swing.JButton btnsort;
    private javax.swing.JButton graficar;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlbElems1;
    private javax.swing.JScrollPane jspElems;
    private javax.swing.JScrollPane jspElemsOrd;
    private javax.swing.JLabel lblcant;
    private javax.swing.JList listinser;
    private javax.swing.JList listlemen;
    private javax.swing.JList listmerge;
    private javax.swing.JList listsort;
    private javax.swing.JLabel memoria;
    private javax.swing.JButton savetime;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
